### ISSUE TITLE
Question. connector's state refresh polling time

### ISSUE THREAD

**Issue by Kwanghyuk-Kim** [SmartThingsCommunity/st-schema-nodejs#43]
Hi, 

I would like to know the reason of 6 hours polling time.
why schema connector works per 6 hours for polling ? what's the background of this number ?

Connector app structure
const connector = new SchemaConnector()
  .discoveryHandler((accessToken, response) => {
    /**
     * Discovery request. Respond with a list of devices. Called after installation of the
     *  **_connector and every six hours after that._**
     * @accessToken External cloud access token
     * @response {DiscoveryResponse} Discovery response object
     */
  })

**Comment by bflorian** [comment]
The 6 hour period was selected to provide a fallback, worst-cases eventual consistency, that was not too expensive for either the partner or SmartThings cloud. Substantially shorter periods were considered but not implemented because of the potential cost and load.

The preferred approach for maintaining consistency is for the connector to make pro-active callbacks to update device state and inform SmartThings of added or deleted devices. These proactive state updates are required for Works With SmartThings (WWST) certification.
